version: "3.7"
services:
    php-fpm:
        container_name: php-fpm
        build:
            args:
                user: www
                uid: 1000
            context: ./
            dockerfile: docker/php-fpm/Dockerfile
        image: laravel-image
        volumes:
            - ./:/var/www
        working_dir: /var/www/
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        networks:
            - internal

    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
            args:
                - CHANGE_SOURCE=false
                - PHP_UPSTREAM_CONTAINER=php-fpm
                - PHP_UPSTREAM_PORT=9000
                - http_proxy
                - no_proxy
        volumes:
            - ./:/var/www
            - ./docker/nginx/log:/var/log/nginx
            - ./docker/nginx/sites:/etc/nginx/sites-available
        ports:
            - 80:80
        depends_on:
            - php-fpm
            - node
        networks:
            internal:
                aliases:
                    - ltest.local

    db:
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        ports:
          - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        command: --init-file /docker-entrypoint-initdb.d/init_db.sql
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.220.0/28
